@startuml
class DepertmentDTO {
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + HeadOfDepartment : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
}
@enduml
