@startuml
class ForgetPasswordDTO {
    + Id : string <<get>> <<set>>
    + NewPassword : string <<get>> <<set>>
    + ConfirmPassword : string <<get>> <<set>>
    + ResetToken : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + UserName : string <<get>> <<set>>
}
@enduml
