@startuml
!include .\\RMSAPI\Program.puml
!include .\\RMSAPI\Controllers\BaseAPIController.puml
!include .\\RMSAPI\Data\DataContext.puml
!include .\\RMSAPI\Data\Seeder.puml
!include .\\RMSAPI\Extentions\ApplicationServiceExtention.puml
!include .\\RMSAPI\Extentions\IdentityServicesExtension.puml
!include .\\RMSAPI\Extentions\SeedDatabase.puml
!include .\\RMSAPI\Extentions\SwaggerServiceExtention.puml
!include .\\RMSAPI\Extentions\TimeSpanExtension.puml
!include .\\RMSAPI\Extentions\WebApplicationExtension.puml
!include .\\RMSAPI\Helper\AutoMapperProfile.puml
!include .\\RMSAPI\Helper\Utilities.puml
!include .\\RMSAPI\Interfaces\IBatchRepository.puml
!include .\\RMSAPI\Interfaces\IDepermentRepository.puml
!include .\\RMSAPI\Interfaces\IGenericRepository.puml
!include .\\RMSAPI\Interfaces\IScheduleService.puml
!include .\\RMSAPI\Interfaces\IStudentRepository.puml
!include .\\RMSAPI\Interfaces\ISubjectRepository.puml
!include .\\RMSAPI\Interfaces\ITeacherRepository.puml
!include .\\RMSAPI\Interfaces\ITokenService.puml
!include .\\RMSAPI\Interfaces\IUnitOfWork.puml
!include .\\RMSAPI\Interfaces\IUserRepository.puml
!include .\\RMSAPI\Middleware\ExceptionMiddleware.puml
!include .\\RMSAPI\Services\TokenService.puml
!include .\\RMSAPI\Controllers\Authentication\AuthController.puml
!include .\\RMSAPI\Controllers\ClassSchedules\ScheduleController.puml
!include .\\RMSAPI\Controllers\Depertments\DepertmentController.puml
!include .\\RMSAPI\Controllers\DTO\ApiException.puml
!include .\\RMSAPI\Controllers\DTO\AppUserDTO.puml
!include .\\RMSAPI\Controllers\DTO\BatchDataDTO.puml
!include .\\RMSAPI\Controllers\DTO\CreateScheduleDTO.puml
!include .\\RMSAPI\Controllers\DTO\DepertmentDataDTO.puml
!include .\\RMSAPI\Controllers\DTO\DepertmentDTO.puml
!include .\\RMSAPI\Controllers\DTO\ForgetPasswordDTO.puml
!include .\\RMSAPI\Controllers\DTO\LoginDTO.puml
!include .\\RMSAPI\Controllers\DTO\RefreshTokenDTO.puml
!include .\\RMSAPI\Controllers\DTO\RegisterDTO.puml
!include .\\RMSAPI\Controllers\DTO\ScheduleDTO.puml
!include .\\RMSAPI\Controllers\DTO\ScheduleEntryDTO.puml
!include .\\RMSAPI\Controllers\DTO\StudentDataDTO.puml
!include .\\RMSAPI\Controllers\DTO\StudentDTO.puml
!include .\\RMSAPI\Controllers\DTO\TeacherDataDTO.puml
!include .\\RMSAPI\Controllers\DTO\TeacherUpdateDTO.puml
!include .\\RMSAPI\Controllers\DTO\TimeSlotDTO.puml
!include .\\RMSAPI\Controllers\DTO\UpdateScheduleDTO.puml
!include .\\RMSAPI\Controllers\DTO\UserDTO.puml
!include .\\RMSAPI\Controllers\DTO\WeeklyScheduleDTO.puml
!include .\\RMSAPI\Controllers\User\UserController.puml
!include .\\RMSAPI\Data\Entities\AppRole.puml
!include .\\RMSAPI\Data\Entities\AppUser.puml
!include .\\RMSAPI\Data\Entities\AppUserRole.puml
!include .\\RMSAPI\Data\Entities\Batch.puml
!include .\\RMSAPI\Data\Entities\BatchSubjects.puml
!include .\\RMSAPI\Data\Entities\Depertment.puml
!include .\\RMSAPI\Data\Entities\Photo.puml
!include .\\RMSAPI\Data\Entities\Routine.puml
!include .\\RMSAPI\Data\Entities\Schedule.puml
!include .\\RMSAPI\Data\Entities\Student.puml
!include .\\RMSAPI\Data\Entities\Subject.puml
!include .\\RMSAPI\Data\Entities\Teacher.puml
!include .\\RMSAPI\Data\Entities\TeacherSubjects.puml
!include .\\RMSAPI\Data\Entities\TimeSlot.puml
!include .\\RMSAPI\Data\Enums\SubjectType.puml
!include .\\RMSAPI\Data\Enums\Themes.puml
!include .\\RMSAPI\Data\Enums\UserType.puml
!include .\\RMSAPI\Data\Migrations\20240329183656_init.puml
!include .\\RMSAPI\Data\Migrations\20240329183656_init.Designer.puml
!include .\\RMSAPI\Data\Migrations\20240331130024_IdentityAdded.puml
!include .\\RMSAPI\Data\Migrations\20240331130024_IdentityAdded.Designer.puml
!include .\\RMSAPI\Data\Migrations\20240331130213_IdentityAdded2.puml
!include .\\RMSAPI\Data\Migrations\20240331130213_IdentityAdded2.Designer.puml
!include .\\RMSAPI\Data\Migrations\20240507105902_AddedAditionUserinfo.puml
!include .\\RMSAPI\Data\Migrations\20240507105902_AddedAditionUserinfo.Designer.puml
!include .\\RMSAPI\Data\Migrations\20240509132922_AddedBatchandothers.puml
!include .\\RMSAPI\Data\Migrations\20240509132922_AddedBatchandothers.Designer.puml
!include .\\RMSAPI\Data\Migrations\20240510125847_addedbatchStudentrelatioship.puml
!include .\\RMSAPI\Data\Migrations\20240510125847_addedbatchStudentrelatioship.Designer.puml
!include .\\RMSAPI\Data\Migrations\20240520085404_AddedSchedule.puml
!include .\\RMSAPI\Data\Migrations\20240520085404_AddedSchedule.Designer.puml
!include .\\RMSAPI\Data\Migrations\20240520093050_AddTimeSlot.puml
!include .\\RMSAPI\Data\Migrations\20240520093050_AddTimeSlot.Designer.puml
!include .\\RMSAPI\Data\Migrations\DataContextModelSnapshot.puml
!include .\\RMSAPI\Data\Repository\BatchRepository.puml
!include .\\RMSAPI\Data\Repository\DepertmentReporitory.puml
!include .\\RMSAPI\Data\Repository\GenericRepository.puml
!include .\\RMSAPI\Data\Repository\ScheduleService.puml
!include .\\RMSAPI\Data\Repository\StudentRepository.puml
!include .\\RMSAPI\Data\Repository\SubjectRepository.puml
!include .\\RMSAPI\Data\Repository\TeacherRepository.puml
!include .\\RMSAPI\Data\Repository\UnitOfWork.puml
!include .\\RMSAPI\Data\Repository\UserRepository.puml
!include .\\RMSAPI\Controllers\Depertments\Batches\BatchController.puml
!include .\\RMSAPI\Controllers\Depertments\Students\StudentController.puml
!include .\\RMSAPI\Controllers\Depertments\Teachers\TeacherController.puml
!include .\\RMSAPI\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\RMSAPI\obj\Debug\net8.0\RMSAPI.AssemblyInfo.puml
!include .\\RMSAPI\obj\Debug\net8.0\RMSAPI.GlobalUsings.g.puml
!include .\\RMSAPI\obj\Debug\net8.0\RMSAPI.MvcApplicationPartsAssemblyInfo.puml
!include .\\RMSAPI\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\RMSAPI\obj\Release\net8.0\RMSAPI.AssemblyInfo.puml
!include .\\RMSAPI\obj\Release\net8.0\RMSAPI.GlobalUsings.g.puml
@enduml
